Fix EBSVolumeHasSSERule for bool type
Skyscanner/cfripper pull request #214
Opened 2022-03-31 07:38 UTC by w0rmr1d3r

## [1.7.1]
### Fixes
- `EBSVolumeHasSSERule` can now understand `encrypted_status` if modelled as a `bool`.
### Updates
- Updated `EBSVolumeHasSSERule` to iterate only over `AWS::EC2::Volume` resources.

2022-03-31 07:55 UTC, jsoucheiron commented on tests/rules/test_EBSVolumeHasSSERule.py
> +@pytest.mark.parametrize(
Why are we using parametrize here?

2022-03-31 08:02 UTC, jsoucheiron commented on cfripper/rules/ebs_volume_has_sse.py
> +            if encrypted_status is None or encrypted_status is False or encrypted_status.lower() != "true":
This is dangerous:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1830262/161006965-600ab90b-9bac-4fd8-9bb3-cf35c996131c.png">

```suggestion
            if str(encrypted_status).lower() != "true":
```

2022-03-31 18:23 UTC, jsoucheiron commented on tests/rules/test_EBSVolumeHasSSERule.py
> +@pytest.mark.parametrize(
I completely missed that the list has 2 entries, I only saw one :( #FAIL

2022-03-31 18:25 UTC, jsoucheiron approved these changes

2022-04-01 05:28 UTC, oscarbc96 requested changes
let's wait for https://github.com/Skyscanner/pycfmodel/pull/95 to be merged

2022-04-01 10:45 UTC, ocrawford555 approved these changes

2022-04-01 12:09 UTC, merged