Bump pycfmodel to allow resources without properties
Skyscanner/cfripper pull request #222
Opened 2022-04-06 15:08 UTC by w0rmr1d3r

## [1.8.1]
### Improvements
- Bump `pycfmodel` to `0.18.1`.

2022-04-06 15:32 UTC, jsoucheiron requested changes
This does not change the library requirements, just the test requirements. Therefore it should not even require a version bump.

2022-04-07 06:20 UTC, w0rmr1d3r commented
> This does not change the library requirements, just the test requirements. Therefore it should not even require a version bump.

My bad, totally forgot about it.
You are right, updated the minimum required version in [2f79a47](https://github.com/Skyscanner/cfripper/pull/222/commits/2f79a475596420eafaee483b4b13d8d57f8c0354)

2022-04-07 07:18 UTC, oscarbc96 approved these changes

2022-04-07 08:12 UTC, w0rmr1d3r commented
Resolved internally with @jsoucheiron , no need to create a new version of this project since it already accepts the version.

2022-04-07 08:12 UTC, closed without merging